### ISSUE TITLE
Status Window actor.name display

### ISSUE THREAD

**Issue by inVictor282** [EnigmaDragons/LegendaryFrailty#373] opened 2017-11-04 02:21 UTC
Hero’s name seems to be ‘Anselm – The Legend’. The name seems to be too long for the actor.name display, making his class overlay on top of the actor’s name.

**Comment by SilasReinagel** [comment] 2017-11-04 02:51
This is a duplicate of EnigmaDragons/LegendaryFrailty#88

**Closed as completed by SilasReinagel** 2017-11-04 02:51 UTC
Labels: duplicate
